print "tests ready"

raise Exception("error de prueba")